### ISSUE TITLE
Regression on BaseQuery.Clone, Join `On` missing

### ISSUE THREAD

**Issue by raphaelvigee** [stephenafamo/bob#47]
BaseQuery.Clone used to correctly clone Joins (tested in 760affdc5a7c), and since [v0.20.1](https://github.com/stephenafamo/bob/releases/tag/v0.20.1) Join.On comes as `nil`

**Comment by stephenafamo** [comment]
I replaced `jinzhu/copier` with `huandu/go-clone` and that seems to have fixed the bug.

I've tagged `v0.20.3` with the fix. Let me know if you continue experiencing any issues.

**Comment by raphaelvigee** [comment]
Upon upgrading, i get this:
```
# github.com/stephenafamo/bob/expr
/Users/rvigee/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/query.go:41:20: internal compiler error: method WriteSQL on struct { query string; args []any } not found
```

**Comment by stephenafamo** [comment]
Can you share a snippet of code I can use to replicate? Maybe a small example of the query that is causing these issues.

**Comment by raphaelvigee** [comment]
Okay this seems to be an 1.19 issue, fixed by upgrading to 1.20, here is `go build -x`:
```
WORK=/var/folders/p2/z4h94_g1745dxgtn7h72kjfr0000gn/T/go-build743625324
cd /Users/me/Documents/Code/myproject
git status --porcelain
cd /Users/me/Documents/Code/myproject
git -c log.showsignature=false show -s --format=%H:%ct
mkdir -p $WORK/b242/
cat >$WORK/b242/importcfg << 'EOF' # internal
# import config
packagefile errors=/opt/homebrew/Cellar/go/1.19/libexec/pkg/darwin_arm64/errors.a
packagefile fmt=/opt/homebrew/Cellar/go/1.19/libexec/pkg/darwin_arm64/fmt.a
packagefile github.com/stephenafamo/bob=/Users/me/Library/Caches/go-build/ce/ce799c6496c33702ac4c17a8b68f4a56cfc486227e2b4c28b180cf2350df1eb6-d
packagefile io=/opt/homebrew/Cellar/go/1.19/libexec/pkg/darwin_arm64/io.a
packagefile strings=/opt/homebrew/Cellar/go/1.19/libexec/pkg/darwin_arm64/strings.a
EOF
cd /Users/me/Documents/Code/myproject
/opt/homebrew/Cellar/go/1.19/libexec/pkg/tool/darwin_arm64/compile -o $WORK/b242/_pkg_.a -trimpath "$WORK/b242=>" -p github.com/stephenafamo/bob/expr -lang=go1.18 -complete -buildid -Fulx9cDjVydbBx8KwyG/-Fulx9cDjVydbBx8KwyG -goversion go1.19 -shared -c=4 -nolocalimports -importcfg $WORK/b242/importcfg -pack /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/arg.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/builder.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/chain.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/constants.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/group.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/operators.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/quote.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/raw.go /Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/expr/string.go
# github.com/stephenafamo/bob/expr
/Users/me/go/pkg/mod/github.com/stephenafamo/bob@v0.20.3/query.go:41:20: internal compiler error: method WriteSQL on struct { query string; args []any } not found

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

**Comment by raphaelvigee** [comment]
But after upgrading, there is still some issue:
```
reflect.Set: value of type int is not assignable to type context.emptyCtx

goroutine 7 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/99designs/gqlgen/graphql.DefaultRecover({0x140002bb3d8?, 0x102d914d0?}, {0x1036cecc0?, 0x14000295650?})
	/Users/me/go/pkg/mod/github.com/99designs/gqlgen@v0.17.28/graphql/recovery.go:17 +0x78
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x140002bb458?, {0x103855020, 0x140002c6600}, {0x1036cecc0?, 0x14000295650?})
	/Users/me/go/pkg/mod/github.com/99designs/gqlgen@v0.17.28/graphql/context_operation.go:124 +0x44
myproject/cloud/graph.(*executionContext)._Query_projects.func1()
	/Users/me/Documents/Code/myproject/cloud/graph/generated.go:3998 +0x68
panic({0x1036cecc0, 0x14000295650})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/panic.go:884 +0x204
reflect.Value.assignTo({0x1036ce3c0?, 0x103db0320?, 0x10386ec01?}, {0x103535ecc, 0xb}, 0x1036c6840, 0x0)
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/reflect/value.go:3245 +0x208
reflect.Value.Set({0x1036c6840?, 0x1400021bff8?, 0x1400003e0b0?}, {0x1036ce3c0?, 0x103db0320?, 0x1?})
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/reflect/value.go:2236 +0xc8
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781ec0?, 0x1400003e0b0?, 0x0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:229 +0x37c
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781ec0?, 0x1400003e0b0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002a0de0?, 0x140002c6ba0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a0de0?, 0x140002a0de0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002a0de0?, 0x1030f6884?}, {0x103781f60?, 0x140002c6ba0?, 0x140002bba58?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002a0de0?, 0x1?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002a0de0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002a0ea0?, 0x140002c6b70?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a0ea0?, 0x140002a0ea0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002a0ea0?, 0x1030f6884?}, {0x103781f60?, 0x140002c6b70?, 0x140002bbe48?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002a0ea0?, 0x1?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002a0ea0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037fafc0?, {0x10375f800?, 0x140002a67d0?, 0x140002a6b40?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a67d0?, 0x140002a67d0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037fafc0?, 0x140002a67d0?, 0x1030f6884?}, {0x103794680?, 0x140002a6b40?, 0x140002bc238?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103794680?, 0x140002a67d0?, 0x6?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103794680?, 0x140002a67d0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037fafc0?, {0x10375f800?, 0x140002a6820?, 0x140002a6af0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a6820?, 0x140002a6820?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037fafc0?, 0x140002a6820?, 0x1030f6884?}, {0x103794680?, 0x140002a6af0?, 0x140002bc628?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103794680?, 0x140002a6820?, 0x140002bc938?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103794680?, 0x140002a6820?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002a0fc0?, 0x140002c6b40?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a0fc0?, 0x140002a0fc0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002a0fc0?, 0x1030f6884?}, {0x103781f60?, 0x140002c6b40?, 0x140002bca18?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002a0fc0?, 0x102d4c1c8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002a0fc0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002a0ff0?, 0x140002c6b10?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a0ff0?, 0x140002a0ff0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002a0ff0?, 0x1030f6884?}, {0x103781f60?, 0x140002c6b10?, 0x140002bce08?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002a0ff0?, 0x1030f5ae0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002a0ff0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002a1050?, 0x140002c6ae0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a1050?, 0x140002a1050?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002a1050?, 0x1030f6884?}, {0x103781f60?, 0x140002c6ae0?, 0x140002bd1f8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002a1050?, 0x10386eca8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002a1050?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002a1080?, 0x140002c6ab0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a1080?, 0x140002a1080?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002a1080?, 0x1030f6884?}, {0x103781f60?, 0x140002c6ab0?, 0x140002bd5e8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002a1080?, 0x102e03960?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002a1080?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002a11d0?, 0x140002c6a80?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002a11d0?, 0x140002a11d0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002a11d0?, 0x1030f6884?}, {0x103781f60?, 0x140002c6a80?, 0x140002bd9d8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002a11d0?, 0x102dfe368?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002a11d0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002c6390?, 0x140002c6a50?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002c6390?, 0x140002c6390?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002c6390?, 0x1030f6884?}, {0x103781f60?, 0x140002c6a50?, 0x140002bddc8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002c6390?, 0x1030f4704?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002c6390?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002c6450?, 0x140002c6a20?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002c6450?, 0x140002c6450?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002c6450?, 0x1030f6884?}, {0x103781f60?, 0x140002c6a20?, 0x140002be1b8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002c6450?, 0x102d4c1c8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002c6450?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002c6480?, 0x140002c69f0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002c6480?, 0x140002c6480?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002c6480?, 0x1030f6884?}, {0x103781f60?, 0x140002c69f0?, 0x140002be5a8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002c6480?, 0x17?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002c6480?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002c64b0?, 0x140002c69c0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002c64b0?, 0x140002c64b0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002c64b0?, 0x1030f6884?}, {0x103781f60?, 0x140002c69c0?, 0x140002be998?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002c64b0?, 0x102e06fbc?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002c64b0?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002c6510?, 0x140002c6990?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002c6510?, 0x140002c6510?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002c6510?, 0x1030f6884?}, {0x103781f60?, 0x140002c6990?, 0x140002bed88?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002c6510?, 0x3?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002c6510?, 0x103660082?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037daa80?, {0x10375f800?, 0x140002c6600?, 0x140002c6960?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x140002c6600?, 0x140002c6600?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037daa80?, 0x140002c6600?, 0x199?}, {0x103781f60?, 0x140002c6960?, 0x1037ac200?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x103781f60?, 0x140002c6600?, 0x1036fb100?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x103781f60?, 0x140002c6600?, 0x0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).cloneInterface(0x1037ac200?, {0x10375f800?, 0x1400023bd98?, 0x14000297b40?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:141 +0x114
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x10375f800?, 0x1400023bd98?, 0x1400023bd98?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:97 +0x134
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1037ac200?, 0x1400023bd98?, 0x0?}, {0x1037a3440?, 0x14000297b40?, 0x140002bf598?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).cloneStruct(0x140002bfb88, {0x1037ac200?, 0x1400023bd98?, 0x140002c8000?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:297 +0xa8
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x1037ac200?, 0x1400023bd98?, 0x140002c81e0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:105 +0x1d4
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x10382bb60?, 0x1400023bb80?, 0x102d4c674?}, {0x1038324a0?, 0x140002c8000?, 0x1?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).clonePtr(0x140002bfb88, {0x1038324a0?, 0x1400000dcb0?, 0x1400000dcc8?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:225 +0x338
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x1038324a0?, 0x1400000dcb0?, 0x1400000dcb0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:101 +0x174
github.com/huandu/go-clone.(*cloneState).copyStruct(0x140002bfb88, {0x1038128e0?, 0x1400000dcb0?, 0x1?}, {0x1037ef7c0?, 0x1400000dcc8?, 0x2?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:365 +0x14c
github.com/huandu/go-clone.(*cloneState).cloneStruct(0x140002bfb88, {0x1038128e0?, 0x1400000dcb0?, 0x10371b380?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:297 +0xa8
github.com/huandu/go-clone.(*cloneState).clone(0x140002bfb88, {0x1038128e0?, 0x1400000dcb0?, 0x10384d520?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:105 +0x1d4
github.com/huandu/go-clone.(*Allocator).clone(0x10417bfc8?, {0x1038128e0?, 0x1400000dcb0?, 0x103e12ba0?}, 0xb0?)
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/allocator.go:114 +0x4c
github.com/huandu/go-clone.clone(0x140002bfd60?, {0x1038128e0?, 0x1400000dcb0?})
	/Users/me/go/pkg/mod/github.com/huandu/go-clone@v1.6.0/clone.go:45 +0xd0
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:3089 +0x520
```

**Comment by stephenafamo** [comment]
Can you share the query that triggers this issue?

It looks like some sort of infinite loop, I have an idea of how to fix but I will like to be able to test out the fix with your query

**Comment by raphaelvigee** [comment]
I have tried pretty hard to repro it, but i m not sure whats causing it, my queries are partially auto generated...
I tried a bunch of copy libs, and github.com/qdm12/reprint seems to work for some reason

**Comment by stephenafamo** [comment]
Can you try using the **Slowly** function in `go-clone`?

**Comment by raphaelvigee** [comment]
Doesnt work either...

**Comment by raphaelvigee** [comment]
I would say that hand-crafting Clone() on all the bob structs would be a lot better, more reliable, faster and less memory utilization

**Comment by stephenafamo** [comment]
> I would say that hand-crafting Clone() on all the bob structs would be a lot better, more reliable, faster and less memory utilization

True. If you can send a PR for this, I would appreciate it.

I think a good design would be to use the hand-crafted function if it supports it, and fallback to a general function

**Comment by stephenafamo** [comment]
Switch `go-clone` to `reprint` in 3569166

Also added a fallback if the Expression contains a `Clone` method. Now we'd only need to handcraft clone methods for each query with tests to ensure.

**Comment by raphaelvigee** [comment]
Awesome, works great!

**Comment by stephenafamo** [comment]
I've tagged `v0.20.4`, so you can use tagged releases again.
